version: "3.8"

services:
  whoami:
    image: registry.example.com/swarm-nginx:${CI_PIPELINE_ID}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.nginx.rule=Host(`nginx.exmaple.com`)"
        - "traefik.http.routers.nginx.entrypoints=http"
        - "traefik.http.routers.nginx.service=nginx"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 30s
      resources:
        limits:
           cpus: "0.5"
           memory: 10M
        reservations:
          cpus: '0.1'
          memory: 5M
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role==worker
    healthcheck:
      test: service nginx status || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - web

networks:
  web:
    external: true
